### ISSUE TITLE
Slider doesn't work properly on mobile

### ISSUE THREAD

**Issue by caffwydev** [ActualMasterOogway/Fluent-Renewed#1]
The ui looks sexy, for some reason the transparency looks better now BUT there's a problem:
The slide won't slide correctly on mobile, i struggle to move the slider on mobile, it's a problem i've had with fluent before (i solved by modifying the slider circle size, not recommended, it may break the slider border limit, its a temporary workaround)

**Comment by ActualMasterOogway** [comment]
I'll check that out

**Comment by ActualMasterOogway** [comment]
Do u think making the display text a text box fix the issue?
