### ISSUE TITLE
Sliders do not fire the `Callback` function when sliding.

### ISSUE THREAD

**Issue by ATrainz** [ActualMasterOogway/Fluent-Renewed#10]
As said in the title, sliders do not fire the `Callback` function when changed

Testing slider here:

```lua
local Fluent = loadstring(game:HttpGetAsync("https://github.com/ActualMasterOogway/Fluent-Renewed/releases/latest/download/Fluent.luau"))()
local Window = Fluent:CreateWindow({
    Title = "testing window",
    SubTitle = "hi",
    TabWidth = 160,
    Size = UDim2.fromOffset(580, 460),
    Acrylic = false,
    Theme = "Dark",
    MinimizeKey = Enum.KeyCode.RightControl
})

local Tab = Window:CreateTab({ Title = "Test", icon = "book" })

Tab:CreateSlider('Gravity', {
    Title = 'Gravity',
    Default = 196.2,
    Min = 0,
    Max = 500,
    Rounding = 1,
    Compact = false,

    Callback = function(Value)
		warn("Gravity changed:", Value)
                workspace.Gravity = Value
    end
})
```

 - Executor: Xeno & Solara
 - OS: Windows Build 22H2
 - Fluent Version: Latest

**Comment by ActualMasterOogway** [comment]
Hi there,

is there any Error in the console?

**Comment by ATrainz** [comment]
> Hi there,
> 
> is there any Error in the console?

None at all.

**Comment by ActualMasterOogway** [comment]
> None at all.

Does the Slider from the example script work for you?

**Comment by ATrainz** [comment]
> > None at all.
> 
> Does the Slider from the example script work for you?

yeah, i can slide it and stuff but it doesn't fire the callback

**Comment by ATrainz** [comment]
> > None at all.
> 
> Does the Slider from the example script work for you?

Sorry if its too much for you, just suggesting a feature.

You know Input's right? Theres `Numeric` and `Finished` properties for it
If you press enter while typing in the textbox, the textbox clears

I was wondering if you could add a `ClearOnFocus` property that sets TextBox.ClearTextOnFocus = true

**Comment by ATrainz** [comment]
> > > None at all.
> > 
> > 
> > Does the Slider from the example script work for you?
> 
> Sorry if its too much for you, just suggesting a feature.
> 
> You know Input's right? Theres `Numeric` and `Finished` properties for it If you press enter while typing in the textbox, the textbox clears
> 
> I was wondering if you could add a `ClearOnFocus` property that sets the `TextBox.ClearTextOnFocus` property. And if you want another idea return the GUI Element itself like `Options.MyInput.Instance`
> 
> Thank you for making Fluent Renewed by the way, its awesome

**Comment by ActualMasterOogway** [comment]
> > > None at all.
> > 
> > Does the Slider from the example script work for you?
> 
> Sorry if its too much for you, just suggesting some features.
> 
> You know Input's right? Theres `Numeric` and `Finished` properties for it
> If you press enter while typing in the textbox, the textbox clears
> 
> I was wondering if you could add a `ClearOnFocus` property that sets `TextBox.ClearTextOnFocus = true`
> And if you want another idea return the GUI Element itself like `Options.MyInput.Instance`
> 
> Thank you for making Fluent Renewed by the way, its awesome

Yeah sure ill work on that, still trying to figure out why it's not working for you. Could u open 2 separate issues for the suggestions so I can mark them as completed before I make a new Release?

**Comment by ATrainz** [comment]
> Yeah sure ill work on that, still trying to figure out why it's not working for you. Could u open 2 separate issues for the suggestions so I can mark them as completed before I make a new Release?

Done, Just a question by the way, I saw zeke hub had keybinds on toggles in one element, How can I do that?

**Comment by ActualMasterOogway** [comment]
Hi there,

[Done](https://github.com/ActualMasterOogway/Fluent-Renewed/commit/ab1c143dda42c1804ff448681079f10c0891bba7).

Best Regards, Oogway

**Comment by ActualMasterOogway** [comment]
> > Yeah sure ill work on that, still trying to figure out why it's not working for you. Could u open 2 separate issues for the suggestions so I can mark them as completed before I make a new Release?
> 
> Done, Just a question by the way, I saw zeke hub (a script using fluent ui) had keybinds on toggles in one element, How can I do that?

I'm not familiar with that feature in Fluent. I might add it someday

**Comment by ActualMasterOogway** [comment]
> > > Yeah sure ill work on that, still trying to figure out why it's not working for you. Could u open 2 separate issues for the suggestions so I can mark them as completed before I make a new Release?
> > 
> > 
> > Done, Just a question by the way, I saw zeke hub (a script using fluent ui) had keybinds on toggles in one element, How can I do that?
> 
> I'm not familiar with that feature in Fluent. I might add it someday

[And that day just came](https://github.com/ActualMasterOogway/Fluent-Renewed/commit/30543a24dcf73035b2e4d29c448921d361ec0d27).
