### ISSUE TITLE
Input Setting "ClearOnEnter"

### ISSUE THREAD

**Issue by ATrainz** [ActualMasterOogway/Fluent-Renewed#11]
My bad, It wasn't `Textbox.ClearTextOnFocus` causing this.

My problem: When pressing enter and focused on a textbox, it clears.
A fix: Add a setting to inputs to clear when enter is pressed or not

**Comment by ActualMasterOogway** [comment]
Hi there,

[Done](https://github.com/ActualMasterOogway/Fluent-Renewed/commit/077ec189ed2d55e94df4b3d6169d7a76d4229d89).

Best Regards, Oogway
