### ISSUE TITLE
Make UI Elements return the instance

### ISSUE THREAD

**Issue by ATrainz** [ActualMasterOogway/Fluent-Renewed#12]
By the instance I mean the parent that holds the entire element (frame and textbox)
Example:
```lua
local Frame = Options.MyInput.Instance
local TextBox = Frame:FindFirstChildWhichIsA("TextBox")
TextBox.TextColor3 = Color3.fromRGB(255,0,0)
```

**Comment by ActualMasterOogway** [comment]
Hi there,

[Done](https://github.com/ActualMasterOogway/Fluent-Renewed/commit/29141b880ba5d4e8e980bdfa0b9343770346e403).

Best Regards, Oogway
