### ISSUE TITLE
New Themes

### ISSUE THREAD

**Issue by ATrainz** [ActualMasterOogway/Fluent-Renewed#14]
I found a script that uses its own modified version of fluent (not better than Fluent Renewed) but it had some cool themes

i was wondering if you could add the themes to Fluent Renewed please
[https://twix.cyou/Fluent.txt](https://twix.cyou/Fluent.txt)

**Comment by ActualMasterOogway** [comment]
Hi there,

[Done](https://github.com/ActualMasterOogway/Fluent-Renewed/commit/e34d5146ed244572a83fb42a94e819ad80e54f5a). I did not add "VSC Dark High Contrast" because it straight up looks like dogwater.

Best Regards, Oogway
