### ISSUE TITLE
New update messed with toggles?

### ISSUE THREAD

**Issue by ATrainz** [ActualMasterOogway/Fluent-Renewed#15]
After the latest update, Toggles seem to take over a second to actually toggle on.
Happened right after the new themes got added (they look cool btw)

I don't know if you would've noticed or not (you probably would've) but just incase I made this post

 - Executor: Xeno
 - OS: Windows Build 22H2
 - Fluent Version: Latest

**Comment by ActualMasterOogway** [comment]
Hi there,

This is what happens when u push to production without throughly testing everything lol. It was probably caused by an attempt to fix the Dropdown:SetValues stuttering.
I'll look into it.

Best Regards, Oogway

**Comment by ActualMasterOogway** [comment]
Hi there,

[fixed](https://github.com/ActualMasterOogway/Fluent-Renewed/commit/ae6b0dfd7f5723ab310da5985432f4e39924ec0e).

Best Regards, Oogway

**Comment by ATrainz** [comment]
> Hi there,
> 
> [fixed](https://github.com/ActualMasterOogway/Fluent-Renewed/commit/ae6b0dfd7f5723ab310da5985432f4e39924ec0e).
> 
> Best Regards, Oogway

Holy crap, Excellent update dude. my script used to freeze whenever loading the UI but now no lag at all.
And the themes are insane too. THANK YOU MASTER OOGWAY

**Comment by altaireh** [comment]
What themes does this UI library have???????
