### ISSUE TITLE
The UI LIbrary is currently detected on the game dragon soul.

### ISSUE THREAD

**Issue by FortniBloxYT1** [ActualMasterOogway/Fluent-Renewed#17]
The UI LIbrary is currently detected on the game dragon soul, it gets detected after like 1 minute of loading the UI in the game then you get perm banned, the same happens with original fluent, yes acrylic is in false and you dont even need to create UI Components, just creating the window will get you banned in like a minute.

**Comment by FortniBloxYT1** [comment]
rayfield is also detected

**Comment by ActualMasterOogway** [comment]
> The UI LIbrary is currently detected on the game dragon soul, it gets detected after like 1 minute of loading the UI in the game then you get perm banned, the same happens with original fluent, yes acrylic is in false and you dont even need to create UI Components, just creating the window will get you banned in like a minute.

Hi there,

this is not a UI issue. Many games are able to detect UIs and every game uses a different method. I cannot fix detections for every game and therefore you should reverse engineer how they detect it and bypass that detection.

Best Regards, Oogway

**Comment by FortniBloxYT1** [comment]
also theres definetely some issue in fluent, because venyx library doesnt get detected and both are parented to coregui, obviously i cant use venyx because its a lib from 2020 and doesnt cover the today standards.
