### ISSUE TITLE
[FEATURE] ColorPicker.UpdateWhileSliding

### ISSUE THREAD

**Issue by ATrainz** [ActualMasterOogway/Fluent-Renewed#18]
When sliding color pickers, it only fires `Callback` and `OnChanged` once you press the `Done` button
`ColorPicker.UpdateWhileSliding` will fire `Callback` and `OnChanged` while you're sliding the color picker.

**Comment by ActualMasterOogway** [comment]
Hi there,

[done](https://github.com/ActualMasterOogway/Fluent-Renewed/commit/dcdb7a60ab69a2e7c0a2554d1cee0ea815563376).

Best Regards, Oogway
