### ISSUE TITLE
[BUG] Toggle Sliding Bug

### ISSUE THREAD

**Issue by ATrainz** [ActualMasterOogway/Fluent-Renewed#19]
Toggles are fine and all, but when sliding them, the visual slider doesn't seem to slide correctly alot of the time.
Sorry for the super crap video quality btw

https://github.com/user-attachments/assets/d99cd445-f94e-45ea-bc20-266cabc22a4f

**Comment by ActualMasterOogway** [comment]
> Toggles are fine and all, but when sliding them, the visual slider doesn't seem to slide correctly alot of the time. Sorry for the super crap video quality btw
> 
>  2024-11-16.01-50-29.mp4

Hi there,

thats a feature, trust me.

Best Regards, Oogway

**Comment by ActualMasterOogway** [comment]
Hi there,

[done](https://github.com/ActualMasterOogway/Fluent-Renewed/commit/b2a6a8f7251876b396326020983cc8c5c5741662).

Best Regards, Oogway
