### ISSUE TITLE
Toggle Keybinds

### ISSUE THREAD

**Issue by ATrainz** [ActualMasterOogway/Fluent-Renewed#20]
I've been trying to use the new toggle keybinds, but everytime I do it, it says keybind isn't a method.
While this post is here, does the keybind toggle off if the actual toggle gets turned off?
![image](https://github.com/user-attachments/assets/941318de-a56c-451e-9e2a-b60dd6c0b4b2)

Example:
```lua
local ToggleKeybind = Tabs.Main:CreateToggle("ToggleWithKeybind", {
    Title = "Toggle",
    Default = false
})

ToggleKeybind:Keybind("KeybindInToggle", {
    Title = "Keybind",
    Default = "X",
	Callback = function(Value)
		print("I've changed!", Value)
	end
})
```
 - Executor: Xeno
 - OS: Windows Build 22H2
 - Fluent Version: Latest

**Comment by ActualMasterOogway** [comment]
Hi there,

those are not finished. I pushed the code but I did not create a release with that feature. I'll make a new release when I'm happy with the current state of the Keybinds.
You can get a copy of the release with that feature in [this run](https://github.com/ActualMasterOogway/Fluent-Renewed/actions/runs/11870110480).

Best Regards, Oogway

**Comment by ATrainz** [comment]
> Hi there,
> 
> those are not finished. I pushed the code but I did not create a release with that feature. I'll make a new release when I'm happy with the current state of the Keybinds. You can get a copy of the release with that feature in [this run](https://github.com/ActualMasterOogway/Fluent-Renewed/actions/runs/11870110480).
> 
> Best Regards, Oogway

ohhh okay

**Comment by ATrainz** [comment]
I know its not finished, but I'm just putting this here incase you don't know about it, theres no option to turn off the keybind, what I was thinking is that if the Toggle is on, then you can activate and deactivate the Keybind, but if it gets turned off, the Keybind also gets turned off.
