### ISSUE TITLE
UI Reopen Button for Mobile

### ISSUE THREAD

**Issue by nmsjayden** [ActualMasterOogway/Fluent-Renewed#23]
**Is your feature request related to a problem? Please describe.**
I know the script isn't exactly meant for mobile but whenever you press the "-" button to hide the UI, you can no longer reopen it as you don't have a keyboard.

**Describe the solution you'd like**
I want a button on-screen that appears when the UI is hidden and makes the UI visible when tapped. This is meant for mobile users who don't have right-shift to reopen it. If you can, make it draggable as well so the user can move it out of the way.

**Additional Context:**
:3

**Comment by SANS3R66** [comment]
wow veri pro thing implementing more than week

**Comment by ActualMasterOogway** [comment]
> wow veri pro thing implementing more than week

I am currently developing additional UI Library features; however, the current state requires further refinement, resulting in a delayed release. I'll release as soon as I'm happy with the current state of the other features 🙂

**Comment by ActualMasterOogway** [comment]
https://github.com/ActualMasterOogway/Fluent-Renewed/commit/9431a563dcd90dfdfb1c23de8e2a32fc6dcb2058
