### ISSUE TITLE
Addition: save ui elements on configs

### ISSUE THREAD

**Issue by joep26020** [ActualMasterOogway/Fluent-Renewed#27]
Saving UI elements like tabs and and elements in the tabs would just be helpful to add and open up a range of possibilities.

**Comment by ActualMasterOogway** [comment]
Are you describing the [Save Manager](https://github.com/ActualMasterOogway/Fluent-Renewed/blob/main/Addons/SaveManager.luau)?

**Comment by joep26020** [comment]
> Are you describing the [Save Manager](https://github.com/ActualMasterOogway/Fluent-Renewed/blob/main/Addons/SaveManager.luau)?

Correct me if im wrong, but does that not save ui elements? like lets say I added a tab or a section, would it not save?

**Comment by joep26020** [comment]
> Are you describing the [Save Manager](https://github.com/ActualMasterOogway/Fluent-Renewed/blob/main/Addons/SaveManager.luau)?

I'm trying to save sections and tabs, but I'm running into many issues and figuring that I pretty much have to make my own save system. It would be a huge favor if you could add saving the actual elements to the save system.

**Comment by ActualMasterOogway** [comment]
Sorry, but in my opinion, saving sections, tabs, etc., is useless because you need to create them at least once to save them. The Save Manager was only designed for elements whose values are not always the same, and this is not the case for tabs and sections
